# Makefile for the UDI Prototype Development Effort: Metalanguage Libraries
#

SHELL=/bin/sh
TOPDIR=../..
OBJDIR=.build
INDIR=mapper/uw
SUBDIRS=bridge gio net scsi

include $(TOPDIR)/env/common/Make_conf.common


DIRS=bridge gio net scsi

real-build real-all real-install::
	@:;    # do nothing
