# Makefile for the FreeBSD UDI mappers

SHELL=/bin/sh
TOPDIR=../..
OBJDIR=.build
INDIR=mapper/freebsd
SUBDIRS=bridge net # gio scsi

include $(TOPDIR)/env/common/Make_conf.common

real-build real-all real-install::
	@:;	# do nothing
