# Makefile for the UDI Prototype Development Effort: Solaris Mappers
#

SHELL=/bin/sh
TOPDIR=../..
OBJDIR=.build
INDIR=mapper/solaris
SUBDIRS=bridge

include $(TOPDIR)/env/common/Make_conf.common

DIRS=bridge

real-build real-all real-install::
	@:;    # do nothing



