/*
 * Automatically generated by make menuconfig: don't edit.
 */

#define AUTOCONF_INCLUDED

/*
 * Kernel & Hardware
 */


/*
 * System Architecture
 */

#define CONFIG_ARCH_x86_64 1
#undef CONFIG_ARCH_AARCH64
#define CONFIG_HW_SSE 1
#undef CONFIG_HW_COMP
#define CONFIG_FM_UEFI 1
#undef CONFIG_FM_BIOS

/*
 * Bootloader settings
 */

#define CONFIG_FM_ACPI 1
#undef CONFIG_FM_SMBIOS

/*
 * Kernel settings
 */

#define CONFIG_KERNEL_CNAME "MicroK"
#define CONFIG_KERNEL_CVER "0.0.0"

/*
 * Drivers
 */

#define CONFIG_UDI 1

/*
 * UDI
 */

#define CONFIG_UDI_VERSION 0x101
#define CONFIG_PCI 1

/*
 * PCI/PCIe device configuration
 */

#define CONFIG_AHCI 1

/*
 * AHCI Settings.
 */

#define CONFIG_AHCI_DMA_SIZE (4194304)

/*
 * Internal Kernel Drivers
 */

#define CONFIG_PRINTK 1
#define CONFIG_HW_GOP 1
#define CONFIG_HW_SERIAL 1

/*
 * VFS
 */

#define CONFIG_VFS 1
#define CONFIG_VFS_MAX_DRIVES (1024)
#define CONFIG_VFS_FILE_MAX_NAME_LENGTH (256)

/*
 * Output images
 */

#undef CONFIG_IMG_ELF
