/*
 * Automatically generated by make menuconfig: don't edit.
 */

#define AUTOCONF_INCLUDED

/*
 * Kernel & Hardware
 */


/*
 * System Architecture
 */

#define CONFIG_ARCH_x86_64 1
#undef CONFIG_ARCH_AARCH64
#define CONFIG_HW_SSE 1
#undef CONFIG_HW_COMP
#define CONFIG_FM_UEFI 1
#undef CONFIG_FM_BIOS

/*
 * Bootloader settings
 */

#define CONFIG_FM_ACPI 1
#undef CONFIG_FM_SMBIOS

/*
 * Kernel settings
 */

#define CONFIG_KERNEL_CNAME "MicroK Vanilla"
#define CONFIG_KERNEL_CVER "0.0.1"

/*
 * Memory Settings
 */

#define CONFIG_KENREL_BASE 0xffffffff80000000
#define CONFIG_STACK_SIZE (4194304)

/*
 * Bootmem allocator
 */

#define CONFIG_BOOTMEM_SIZE (65536)

/*
 * Kernel heap
 */

#define CONFIG_HEAP_BASE 0xffffffff90000000
#define CONFIG_HEAP_SIZE (67108864)

/*
 * Symbol table
 */

#define CONFIG_SYMBOL_TABLE_BASE 0xffffffffffff0000
#define CONFIG_SYMBOL_TABLE_PAGES (8)

/*
 * Drivers
 */


/*
 * Internal Kernel Drivers
 */

#define CONFIG_PRINTK 1
#define CONFIG_HW_SERIAL 1

/*
 * VFS
 */

#define CONFIG_VFS 1
#define CONFIG_VFS_MAX_DRIVES (128)
#define CONFIG_VFS_FILE_MAX_NAME_LENGTH (128)

/*
 * Output images
 */

#define CONFIG_IMG_ELF 1

