#!/bin/ksh

#
# Run the target program with any available test facilities.
#

FILE_TO_RUN=`basename $*`
export MALLOC_CHECKS=" -6"

case $FILE_TO_RUN in
	# ndtest allocates lots of buffers, so we turn down the default
	# checking on that target.
	ndtest) MALLOC_CHECKS=" -5";;
	cmostest) if [ $(id -u -n) != "root" ]; then 
			echo "** You are not root.  Skipping cmostest." 
			exit 0; 
		  fi ;;
	*)	;;
esac

echo "CHECKS='$MALLOC_CHECKS'"
exec  $*
