#!/bin/sh

# Obtain the architecture specific settings for UDI_CC and UDI_CCOPTS so that
# all UDI binaries are built using the same tools
#
# Information is held in ../../tools/solaris/osdep.h and needs to be parsed
# using whatever C preprocessor is available
#

TEMPFILE=test$$.c		# Temporary file for CPP to use

if [ $# -eq 0 ]
then
	targets="UDI_CC UDI_CCOPTS UDI_CCOPTS_MAPPER"
else
	case $1 in
	-targetcc)
		targets=UDI_CC
		;;
	-targetccopts)
		targets=UDI_CCOPTS
		;;
	-targetmapperopts)
		targets=UDI_CCOPTS_MAPPER
		;;
	esac
fi

#
# Determine where the C preprocessor is. If cpp is in the current path we'll use
# that. Otherwise fall back to gcc -E, and then cc -E
#
type cpp > /dev/null 2>&1
if [ $? -eq 0 ]
then
	CPP=cpp
else
	type gcc > /dev/null 2>&1
	if [ $? -eq 0 ]
	then
		CPP="gcc -E"
	else
		CPP="cc -E"
	fi
fi

for targ in $targets
do
	rm -f ${TEMPFILE}
	cat > ${TEMPFILE} <<!EOF
#include "../../tools/solaris/osdep.h"
target=${targ}
!EOF
	set -- `(
		${CPP} ${TEMPFILE}
	) 2>/dev/null | fgrep 'target'`

	shift
	echo $* | sed 's/\" //g' | sed 's/\"//g'
done
rm -f ${TEMPFILE}
