#pragma once
#include "../../config/autoconf.h"

#define KRNLSYMTABLE_REQUESTPAGE 0
#define KRNLSYMTABLE_REQUESTPAGES 1
#define KRNLSYMTABLE_MEMCPY 2
#define KRNLSYMTABLE_MEMSET 3
#define KRNLSYMTABLE_MEMCMP 4
#define KRNLSYMTABLE_PRINTK 5
#define KRNLSYMTABLE_MALLOC 6
#define KRNLSYMTABLE_FREE 7
#define KRNLSYMTABLE_STRCPY 8
#define KRNLSYMTABLE_BUFFERCREATE 9
#define KRNLSYMTABLE_BUFFERIOCTL 10
#define KRNLSYMTABLE_BUFFERDELETE 11

