$ 
$ 
$    Copyright (c) 1995-2001; Compaq Computer Corporation; Hewlett-Packard
$    Company; Interphase Corporation; The Santa Cruz Operation, Inc;
$    Software Technologies Group, Inc; and Sun Microsystems, Inc
$    (collectively, the "Copyright Holders").  All rights reserved.
$ 
$    Redistribution and use in source and binary forms, with or without
$    modification, are permitted provided that the conditions are met:
$ 
$            Redistributions of source code must retain the above
$            copyright notice, this list of conditions and the following
$            disclaimer.
$ 
$            Redistributions in binary form must reproduce the above
$            copyright notice, this list of conditions and the following
$            disclaimers in the documentation and/or other materials
$            provided with the distribution.
$ 
$            Neither the name of Project UDI nor the names of its
$            contributors may be used to endorse or promote products
$            derived from this software without specific prior written
$            permission.
$ 
$    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
$    "AS IS," AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
$    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
$    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
$    HOLDERS OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
$    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
$    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
$    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
$    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
$    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
$    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
$    DAMAGE.
$ 
$    THIS SOFTWARE IS BASED ON SOURCE CODE PROVIDED AS A SAMPLE REFERENCE
$    IMPLEMENTATION FOR VERSION 1.01 OF THE UDI CORE SPECIFICATION AND/OR
$    RELATED UDI SPECIFICATIONS. USE OF THIS SOFTWARE DOES NOT IN AND OF
$    ITSELF CONSTITUTE CONFORMANCE WITH THIS OR ANY OTHER VERSION OF ANY
$    UDI SPECIFICATION.
$ 
$ 
1407	"Udimkpkg is being done for a mapper"
1600	"no handling for %c type %d:\n\t%s\n"
1601	"invalid value for parameter %c\n"
1602	"must specify a valid %s for %c\n"
1603	"need an existing file for %s; %s invalid\n"
1604	"need an existing file for -%c; %s invalid\n"
1605	"need an existing directory for -%c; %s invalid\n"
1606	"directory %s already exists!\n"
1607	"         Try -h for help.\n"
1608	"usage: %s [options]"
1609	"\t  option:     %s\n"
1610	"\t%s\t   keywd"
1611	"\t%s\t   ENV Var: %s [=%s]\n"
1612	"\t%s\t   ENV Var: %s\n"
1613	"\t%s\t   Default: %s\n"
1614	" --- Environment Variable Overrides ---\n"
1615	"\t%s\t   Default: %s\n"
1616	"\t%s\t   Current: %s\n"
1617	" --- UDI Version: %s  ---  ABI: %s \"%s\" ---\n"
1618	"       Max Call Stack Size: "
1619	"      Max Module Data Size: "
1620	"      Max Module File Size: "
1621	"       Max Code per Driver: "
1622	"       Max Data per Driver: "
1623	"                Endianness: %s\n"
1624	"        Object File Format: %s\n"
1625	" Static Properties Binding: %s\n"
1626	"    Package Directory Root: %s\n"
1650	"Show usage info"
1651	"Show FULL usage info"
1652	"Show Version/Config info"
1653	"Verbose output"
1654	"Dryrun: With -v, echo commands only, no execution"
1655	"Temporary directory for udi utilities to use"
1656	"Directory to direct resulting files to"
1657	"Build Debug objects"
1658	"Build Optimized objects"
1659	"Build (update) only objects whose source has changed"
1660	"Udibuild is being done for a mapper"
1661	"Compiler to be used"
1662	"Additional compiler options"
1663	"Linker to be used"
1664	"Additional linker options"
1665	"Specifies distribution type"
1666	"<shortname>"
1667	"Name of the driver being packaged"
1668	"<release>"
1669	"Name of the package alternative"
1670	"<module>"
1671	"Name of the package component"
1672	"Overwrite any existing output package file"
1673	"Update/combine into existing output package file"
1674	"Stop udisetup prior to install"
1675	"User yes/no to confirm each package & component"
1676	"Quiet mode; minimal output on success"
1677	"Show current UDI setup (no input processed)"
1678	"Udisetup is being done for a mapper"
1679	"Compiler to be used, with any additional options"
1680	"Name of the OS Specific package for this driver"
1681	"[UDI_pkg_file]:The specific udi packaged file to run udisetup on"
1682	"Display info of driver shortname"
