$ 
$ 
$    Copyright (c) 1995-2001; Compaq Computer Corporation; Hewlett-Packard
$    Company; Interphase Corporation; The Santa Cruz Operation, Inc;
$    Software Technologies Group, Inc; and Sun Microsystems, Inc
$    (collectively, the "Copyright Holders").  All rights reserved.
$ 
$    Redistribution and use in source and binary forms, with or without
$    modification, are permitted provided that the conditions are met:
$ 
$            Redistributions of source code must retain the above
$            copyright notice, this list of conditions and the following
$            disclaimer.
$ 
$            Redistributions in binary form must reproduce the above
$            copyright notice, this list of conditions and the following
$            disclaimers in the documentation and/or other materials
$            provided with the distribution.
$ 
$            Neither the name of Project UDI nor the names of its
$            contributors may be used to endorse or promote products
$            derived from this software without specific prior written
$            permission.
$ 
$    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
$    "AS IS," AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
$    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
$    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
$    HOLDERS OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
$    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
$    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
$    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
$    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
$    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
$    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
$    DAMAGE.
$ 
$    THIS SOFTWARE IS BASED ON SOURCE CODE PROVIDED AS A SAMPLE REFERENCE
$    IMPLEMENTATION FOR VERSION 1.01 OF THE UDI CORE SPECIFICATION AND/OR
$    RELATED UDI SPECIFICATIONS. USE OF THIS SOFTWARE DOES NOT IN AND OF
$    ITSELF CONSTITUTE CONFORMANCE WITH THIS OR ANY OTHER VERSION OF ANY
$    UDI SPECIFICATION.
$ 
$ 
1202	"Cannot open %s!\n"
1800	"Unable to open file %s for reading!\n"
1801	"unable to malloc for string table of size %d!\n"
1802	"Elf library out of date!\n"
1803	"%s is not an ELF format file!\n"
1804	"Unable to get ELF file header info for %s!\n"
1805	"unable to malloc space for Elf string data!\n"
1806	"unable to create a new elf section in file %s!\n"
1807	"unable to create a new elf section data in file %s!\n"
1808	"Unable to open file %s for appending!\n"
1809	"Unable to write to output file %s!\n"
1810	"error %d from cat of sprops\n"
1811	"Unable to open file %s for  getting sprops\n"
1812	"Unable to open output props file %s"
1813	"Error: Unable to write to %s in cat request!\n"
1814	"section `%s' of %s contains 0x%x bytes of writeable data\n"
1815	"code section `%s' of %s contains 0x%x bytes; exceeds ABI guarantee of 0x%x bytes\n"
1816	"code section `%s' of %s contains 0x%x bytes; approaching ABI guarantee of 0x%x bytes\n"
1817	"data section `%s' of %s contains 0x%x bytes; exceeds ABI guarantee of 0x%x bytes\n"
1818	"code section `%s' of %s contains 0x%x bytes; approaching ABI guarantee of 0x%x bytes\n"
1819	"code sections of %s contain 0x%x bytes; exceeds ABI guarantee of 0x%x bytes\n"
1820	"code sections of %s contain 0x%x bytes; approaching ABI guarantee of 0x%x bytes\n"
1821	"data sections of %s contain 0x%x bytes; exceeds ABI guarantee of 0x%x bytes\n"
1822	"data sections of %s contain 0x%x bytes; approaching ABI guarantee of 0x%x bytes\n"
1823	" %s contains 0x%x bytes; exceeds ABI guarantee of 0x%x bytes\n"
1824	" %s contains 0x%x bytes; approaching ABI guarantee of 0x%x bytes\n"
2109	"Not an ELF file: %s\n"
2110	"Invalid ELF identifier in %s\n"
2113	"Cannot find .symtab or .strtab in %s\n"
