$ 
$ 
$    Copyright (c) 1995-2001; Compaq Computer Corporation; Hewlett-Packard
$    Company; Interphase Corporation; The Santa Cruz Operation, Inc;
$    Software Technologies Group, Inc; and Sun Microsystems, Inc
$    (collectively, the "Copyright Holders").  All rights reserved.
$ 
$    Redistribution and use in source and binary forms, with or without
$    modification, are permitted provided that the conditions are met:
$ 
$            Redistributions of source code must retain the above
$            copyright notice, this list of conditions and the following
$            disclaimer.
$ 
$            Redistributions in binary form must reproduce the above
$            copyright notice, this list of conditions and the following
$            disclaimers in the documentation and/or other materials
$            provided with the distribution.
$ 
$            Neither the name of Project UDI nor the names of its
$            contributors may be used to endorse or promote products
$            derived from this software without specific prior written
$            permission.
$ 
$    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
$    "AS IS," AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
$    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
$    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
$    HOLDERS OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
$    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
$    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
$    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
$    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
$    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
$    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
$    DAMAGE.
$ 
$    THIS SOFTWARE IS BASED ON SOURCE CODE PROVIDED AS A SAMPLE REFERENCE
$    IMPLEMENTATION FOR VERSION 1.01 OF THE UDI CORE SPECIFICATION AND/OR
$    RELATED UDI SPECIFICATIONS. USE OF THIS SOFTWARE DOES NOT IN AND OF
$    ITSELF CONSTITUTE CONFORMANCE WITH THIS OR ANY OTHER VERSION OF ANY
$    UDI SPECIFICATION.
$ 
$ 
1200	"invalid declaration on line %d in file %s!\n"
1201	"Unable to allocate memory for the input table!\n"
1202	"Cannot open %s!\n"
1203	"Must be exactly one '%s' declaration!\n"
1204	"One or more '%s' declaration(s) required!\n"
1205	"Missing 'region' declaration for region zero!\n"
1206	"the first non-comment line for the static properties was\n\tnot the properties_version line!\n"
1207	"invalid static properties version specified!\n"
1208	"These tools support the following version(s): %s\n"
1209	"Unable to allocate more memory for the input table!\n"
1210	"Unable to allocate memory for an entry!\n"
1211	"Unable to allocate memory for a string!\n"
1212	"invalid string specified on line %d!\n"
1213	"invalid attribute value (%s) for attribute\ntype %s, specified on line %d!\n"
1214	"invalid attribute type (%s) specified on line %d!\n"
1215	"invalid region attribute value (%s) near line %d!\n"
1216	"invalid region attribute (%s) near line %d!\n"
1217	"region attribute provided with no value (%s) near line %d!\n"
1218	"invalid symbols declaration near line %d!\n"
1219	"no choices specified for a custom or config_choices declaration near line %d!\n"
1220	"invalid attr_type (%s) in the declaration near line %d!\n"
1221	"no values were used with range in mutex declaration near line %d!\n"
1222	"mismatch of value type with mutex in declaration near line %d!\n"
1223	"invalid attr_type was used with range in custom declaration near line %d!\n"
1224	"min_value was greater than max_value in custom declaration near line %d!\n"
1225	"invalid range was defined in custom declaration near line %d!\n"
1226	"invalid <msgnum> declared in custom declaration near line %d!\n"
1227	"invalid scope (%s) for a custom declaration near line %d!\n"
1228	"invalid filename specified on line %d!\n"
1229	"invalid filespec specified on line %d!\n"
1230	"invalid message number %d specified on line %d!\n"
1231	"invalid value for region attribute overrun_time (%d), near line %d!\n"
1232	"size of array exceeded %d characters!\n"
1233	"invalid value (%s) for declaration type %s, specified on line %d!\nMust be in the range of 0 - 255.\n"
1234	"invalid value (%s) for declaration\ntype %s, specified on line %d!\n"
1235	"invalid number of parameters declared in custom declaration near line %d!\n"
1236	"invalid interface name (%s) for provides declaration on line %d!\n"
1237	"invalid version_number (%s) for provides declaration on line %d!\n"
1240	"`%s' declaration not allowed with `%s' @ line %d\n"
1241	"`%s' declaration invalid for %s @ line %d\n"
1242	"`%s' declaration not allowed in a %s (@ line %d)\n"
1243	"multiple `%s' declarations not allowed (@ line %d)\n"
1244	"invalid compile_option `%s' at line %d)\n"
