$ 
$ 
$    Copyright (c) 1995-2001; Compaq Computer Corporation; Hewlett-Packard
$    Company; Interphase Corporation; The Santa Cruz Operation, Inc;
$    Software Technologies Group, Inc; and Sun Microsystems, Inc
$    (collectively, the "Copyright Holders").  All rights reserved.
$ 
$    Redistribution and use in source and binary forms, with or without
$    modification, are permitted provided that the conditions are met:
$ 
$            Redistributions of source code must retain the above
$            copyright notice, this list of conditions and the following
$            disclaimer.
$ 
$            Redistributions in binary form must reproduce the above
$            copyright notice, this list of conditions and the following
$            disclaimers in the documentation and/or other materials
$            provided with the distribution.
$ 
$            Neither the name of Project UDI nor the names of its
$            contributors may be used to endorse or promote products
$            derived from this software without specific prior written
$            permission.
$ 
$    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
$    "AS IS," AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
$    LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
$    A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
$    HOLDERS OR ANY CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
$    INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
$    BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
$    OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
$    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
$    TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
$    USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
$    DAMAGE.
$ 
$    THIS SOFTWARE IS BASED ON SOURCE CODE PROVIDED AS A SAMPLE REFERENCE
$    IMPLEMENTATION FOR VERSION 1.01 OF THE UDI CORE SPECIFICATION AND/OR
$    RELATED UDI SPECIFICATIONS. USE OF THIS SOFTWARE DOES NOT IN AND OF
$    ITSELF CONSTITUTE CONFORMANCE WITH THIS OR ANY OTHER VERSION OF ANY
$    UDI SPECIFICATION.
$ 
$ 
1507	"unable to open UDI distribution format package directory\n"
1510	"unable to change to UDI driver directory: %s\n"
1514	"No bin or src directory in %s\n"
1516	"multiple alt_yyy in package not implemented\n"
1517	"Package file    : %s\n"
1518	"Install from package file: %s "
1519	"..Driver        : %s\n"
1520	"Install Driver %s "
1521	"....Alternative : %s\n"
1522	"......Component : %s\n"
1523	"Building component from source...\n"
1524	"src build failed"
1525	"........Name    : %s\n"
1526	"........Category: %s\n"
1527	"........Release : %s\n"
1528	"........Supplier: %s\n"
1529	"........Contact : %s\n"
1530	"........Module  : %s\n"
1531	"........ShortNam: %s\n"
1532	"no supplier id!\n"
1533	"no shortname!\n"
1534	"........Device  : %s\n"
