# Makefile for the UDI Prototype Development Effort: Metalanguage Libraries
#

SHELL=/bin/sh
TOPDIR=../..
OBJDIR=.build
INDIR=mapper/osr5
#SUBDIRS=bridge gio net scsi tstgio
SUBDIRS=bridge gio net scsi

include $(TOPDIR)/env/common/Make_conf.common


real-build real-all real-install::
	@:;    # do nothing

