#!/bin/ksh


TOPDIR=$(dirname $0)
while :
do
	[ -d ${TOPDIR}/../udiref ] && {
		break;
	}
	TOPDIR=${TOPDIR}"/.."
done

COPYDIR="${TOPDIR}/tools/copyrights"

for f in $*
do
	file $f | grep -i text > /dev/null || { 
		echo $f is not a text file.  Skipping.
		continue
	}
	awk -f ${COPYDIR}/fixup.awk $f  > $f.$$ &&  { 
		# Only replace the file if it actually differs.
		if  cmp -s $f.$$ $f ;
		then
			rm $f.$$
		else
 			mv $f.$$ $f
		fi
	}
done
